version: "3"

vars:
  LORELINE_DB_DSN: '{{.LORELINE_DB_DSN | default ""}}'

tasks:
  help:
    desc: print this help message
    cmds:
      - task --list-all
    silent: true

  confirm:
    desc: confirmation prompt
    cmds:
      - |
        echo -n 'Are you sure? [y/N] ' && read ans && [ ${ans:-N} = y ]
    silent: true
    internal: true

  run:
    desc: run the cmd/loreline application
    cmds:
      - go run ./cmd/loreline

  dev:
    desc: run the cmd/loreline application with Air live reload
    cmds:
      - go run github.com/air-verse/air@v1.67.3 -c .air.toml

  build:
    desc: build the cmd/loreline application
    cmds:
      - go build -o ./bin/loreline ./cmd/loreline

  migrations:new:
    desc: create a new database migration
    vars:
      NAME: '{{.name | default ""}}'
    cmds:
      - |
        if [ -z "{{.NAME}}" ]; then
          echo "Error: name parameter is required"
          echo "Usage: task migrations:new name=migration_name"
          exit 1
        fi
      - echo 'Creating migration file for {{.NAME}}...'
      - tern new -m ./internal/database/migrations {{.NAME}}

  migrations:up:
    desc: apply all up database migrations
    deps: [confirm]
    cmds:
      - echo 'Running up migrations...'
      - tern migrate -m ./internal/database/migrations --conn-string {{.LORELINE_DB_DSN}}

  tidy:
    desc: format all .go files, and tidy and vendor module dependencies
    cmds:
      - echo 'Formatting .go files...'
      - go fmt ./...
      - echo 'Tidying module dependencies...'
      - go mod tidy
      - echo 'Verifying dependencies...'
      - go mod verify
